baseURL: 'https://fontysvenlo.github.io/prc2/'
languageCode: en-us
title: PRC2
theme: sebi-theme
sectionPagesMenu: main
params:
  highlight: true
  github: https://github.com/FontysVenlo/prc2
  fontawesome: true
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^asciidoctor$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
markup:
  tableOfContents:
    endLevel: 3
  asciidocext:
#    backend: html5s
    failureLevel: warn
    # extensions:
    #   - "asciidoctor-html5s"
    attributes:
      toc: true
      toclevels: 2
      topics: topics
      imagesdir: /prc2/images
      icons: font
