# You can add comments here.

# hosts and ports are plural
# to be able to connect to multiple hosts and ports

# Make sure that you don't push this file to a repository, as it contains sensitive information such as database credentials.

dbname=aisdb
user=aisuser
password=aispassword
hosts=localhost