== Test Recipe I, Test Equals and hashCode

We may sprinkle our testing stuff with a few recipes for often occurring tests.
This is the the first installment.

*Equals* and *hashCode* are not twins in the direct sense, but indeed methods whose implementation should
have a very direct connection.
From the java https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Object.html#hashCode()[Object API ^] follows
 that:

* Two objects that are equal by their equal method, than their hashCode should also be equal.
* Note that the reverse is not true. If two hashCode are the same, that does not imply that the objects are equal.
* A good hashCode 'spreads' the objects well, but this is not a very strict requirement or a requirement that can be enforced. A poor hashCode
  will lead to poor Hash{Map|Set}  lookup performance.

Although hashCodes are invented to speedup finding object in a hash map or hash set, these collections use hashCode in the first part of the search,
but must verify equality as final step(s).

The thing is that the equals method must consider quite a few things, expressed with conditional evaluation (if-then-else).
The good thing is an IDE typically provides a way to generate  equals and hashCode for you and these implementations are typically of good quality. But
in particular the equals method there are quite some ifs, sometimes in disguise, coded as `&&`, so this will throw some flies in your code-coverage ointment.

However, we can balance this generated code by a piece of reusable test code, that can be used for almost all cases.
In fact we have not found a case where it does not apply. +
Let us first explain the usage and then the implementation. +
Suppose you have an object with three fields, `name`, `birthDate` and `id`. All these fields should be considered in equals and hashCode. +
As an exercise, create such and object now in your IDE, call it Student, why not.

[source,java]
----
class Student {
  final String name;
  final LocalDate birthDate;
  final int id;
}
----

From the above, the IDE can generate a *constructor*, *equals* and *hashCode* and *toString*. What are you waiting for? Because it is not test driven?
You would be almost right, but why test drive something that can be generated. +
However, if your spec does [red]*not* demand equals and hashCode,
then [red big]*do not write/generate* them. That would be unwanted code. But if the requirements DO insist on equals and hashCode,
 make sure that the fields to be considered match the requirements. Choose only final fields.

After having such a generated equals and hashCode you have the predicament of writing a test. HashCode is relatively easy. It should produce an
integer, but what value is unspecified, so just invoking it would do the trick for test coverage.
The devil is in the equals details, because it has to consider:

* Is the other object `this`? If yes, return `true`.
* Is the other object `null`? Return `false` if it is.
* Now consider the type.footnote:[Not all equals implementation look at the type of this, See the java.util.List doc for a counter example].
** Is the other of the same type as `this`? If not return `false`.
** Now we are in known terrain, the other is of the same type, so the object has the same fields. +
  For each field test it `this.field.equals(other.field)`. If not return false.
** Using `Objects.equals(this.fieldA, other.fieldB)` can be an efficient solution to avoid testing for nullity of either field.

.Generated equals. It is fine.
[source,java]
----
    @Override
    public boolean equals( Object obj ) {
        if ( this == obj ) {
            return true;
        }
        if ( obj == null ) {
            return false;
        }
        if ( getClass() != obj.getClass() ) {
            return false;
        }
        final Student other = (Student) obj;
        if ( this.id != other.id ) {
            return false;
        }
        if ( !Objects.equals( this.name, other.name ) ) {
            return false;
        }
        return Objects.equals( this.birthDate, other.birthDate );
    }
----

You see a pattern here: The number of ifs is 3 + the number of fields. +
To test this, and to make sure you hit all code paths, you need to test with this,
with null, with an distinct (read newly constructed) object with all fields equal,
and then one for each field, which differs from the reference object only in said field.

Define those instances (for this example) as follows.

.Instances for complete equals and hashCode test and coverage
[source,java]
----
    //@Disabled
    @Test
    void testEqualsAndHash() {
        Student ref = new Student( "Jan", LocalDate.of( 1999, 03, 23 ), 123 );
        Student equ = new Student( "Jan", LocalDate.of( 1999, 03, 23 ), 123 );
        Student sna = new Student( "Jen", LocalDate.of( 1999, 03, 23 ), 123 ); //<1>
        Student sda = new Student( "Jan", LocalDate.of( 1998, 03, 23 ), 123 ); //<2>
        Student sid = new Student( "Jan", LocalDate.of( 1999, 03, 23 ), 456 ); //<3>
        verifyEqualsAndHashCode( ref, equ, sna, sda, sid );
        //fail( "testMethod reached it's and. You will know what to do." );
    }
----

<1> Differs in name.
<2> Differs in birthdate (year).
<3> Differs in id.

The implementation of the `verifyEqualsAndHashCode` has been done with generics and a dash of AssertJ stuff.

.Sample test helper in separate class.
[source,java]
----
    /**
     * Helper for equals tests, which are tedious to get completely covered.
     *
     * @param <T> type of class to test
     * @param ref reference value
     * @param equal one that should test equals true
     * @param unEqual list of elements that should test unequal in all cases.
     */
     public static <T> void verifyEqualsAndHashCode( T ref, T equal, T... unEqual ) {
         Object object = "Hello";
         T tnull = null;
         String cname = ref.getClass().getCanonicalName();
         // I got bitten here, assertJ equalTo does not invoke equals on the
         // object when ref and 'other' are same.
         // THAT's why the first one differs from the rest.
         SoftAssertions.assertSoftly( softly-> {
           softly.assertThat( ref.equals( ref ) )
                   .as( cname + ".equals(this): with self should produce true" )
                   .isTrue();
           softly.assertThat( ref.equals( tnull ) )
                   .as( cname + ".equals(null): ref object "
                           + safeToString( ref ) + " and null should produce false"
                   )
                   .isFalse();
           softly.assertThat( ref.equals( object ) )
                   .as( cname + ".equals(new Object()): ref object"
                           + " compared to other type should produce false"
                   )
                   .isFalse();
           softly.assertThat( ref.equals( equal ) )
                   .as( cname + " ref object [" + safeToString( ref )
                           + "] and equal object [" + safeToString( equal )
                           + "] should report equal"
                   )
                   .isTrue();
           for ( int i = 0; i < unEqual.length; i++ ) {
               T ueq = unEqual[ i ];
               softly.assertThat( ref )
                       .as("testing supposed unequal objects")
               .isNotEqualTo( ueq );
           }
           // ref and equal should have same hashCode
           softly.assertThat( ref.hashCode() )
                   .as( cname + " equal objects "
                           + ref.toString() + " and "
                           + equal.toString() + " should have same hashcode"
                   )
                   .isEqualTo( equal.hashCode() );
        });
     }

    /**
     * ToString that deals with any exceptions that are thrown during its
     * invocation.
     *
     * When x.toString triggers an exception, the returned string contains a
     * message with this information plus class and system hashCode of the
     * object.
     *
     * @param x to turn into string or a meaningful message.
     * @return "null" when x==null, x.toString() when not.
     */
    public static String safeToString( Object x ) {
        if ( x == null ) {
            return "null";
        }
        try {
            return x.toString();
        } catch ( Throwable e ) {
            return "invoking toString on instance "
                    + x.getClass().getCanonicalName() + "@"
                    + Integer.toHexString( System.identityHashCode( x ) )
                    + " causes an exception " + e.toString();
        }
    }
----

The above code has been used before but now adapted for AssertJ and JUnit 5.

It is of course best to put this in some kind of test helper library, so you can reuse it over and over without having to
resort to copy and waste.

'''
