---
title: "Welcome"
date: 2022-02-02T15:04:33+01:00
draft: false
---

== Module description

* Module description can be found on canvas

This site contains the up-to-date course material, exercises and announcements about PRC2
(Programming Concepts 2: the Test Driven Way), starting in February 2022.

Responsible Teachers for 2022 PRC2: 

- Martijn Bonajo
- Ibrahim Kouzak 
- Richard van den Ham

include::{topics}/literature.adoc[]

[TIP]
====
Read the corresponding Horstmann book chapters and do the tutorials before you come to class. This will make
the lessons more effective for you, because the questions that you might have
from studying could be answered immediately. +
Studying is not glancing over some (web) pages, but experimenting with the compiler, IDE and other
tools, to see if you can use the presented ideas and apply it in your own code.
====

include::{topics}/topics.adoc[]

[CAUTION]
.Exercises
====
You should start with the exercises in the week they are listed in and hand them in
by committing your work to your personal *github* repository. +
*Best* is to do that before next week's lesson, so you even if you were not able to
even when trying, you will at least have some questions.

[big red]*We will use a strict deadline policy for the assignments.* +
*The hand in deadline is two lesson weeks after the publication date.*

[bigger red]*Completion of all the exercises grant admission to the performance assessment!*
====

include::{topics}/wow.adoc[]

== MS Teams channel(s)
MSTeams code 2022: nzbu87g 


== Automatic correction of practical exercises.

In PRC1 you have become acquainted with automatic tests. In PRC2 you will not only write the implementation, but also the tests.
These tests need testing too.

The approach to follow is having not only a correct implementation, but also some broken implementations to test your tests.

The ubiquitous question is always: Where do I start?

The answer is surprisingly simple: at the requirements of class, method or whatever you want to develop. And always start at the simple end.
So if a requirement says that a fresh Stack is empty, that means you can write a test that asserts that a `new` instance of your class reports that it is
empty when the `isEmpty()` is called.