---
title: "02 Parameterized tests"
description: ""
date: 2022-02-01T14:17:33+01:00
draft: false
images: []
slug: "parameterized-tests"
menu:
  docs:
    parent: ""
weight: 020
toc: true
---

:imagesdir: /prc2_web/

== Clean tests
Bad tests are anything but a pleasure to work with. They are slow, hard to understand, and hard to maintain.
In order to write clean tests, we follow the F.I.R.S.T. principles of tests:

// Source: Clean code, Robert C. Martin

- **Fast**: Tests should run quickly.
- **Independent**: Tests should not depend on each other. When the state of one test affects the outcome of another, it can be hard to understand why a test fails and makes it harder to run single tests or run tests in parallel.
- **Repeatable**: Tests should be repeatable in any environment. This means that tests should not depend on external resources like databases, network, or file systems.
- **Self-Validating**: Tests should be able to determine if they pass or fail without human intervention. This means that the test should contain assertions that determine if the test passes or fails.
- **Timely**: Tests should be written before the code they test. This is the essence of Test-Driven Development (TDD). If you write tests after the code, you might find out the code is hard to test.

include::{topics}/parameterizedtests.adoc[]

[TIP]
====
Think test driven! So write tests FIRST, and then code. Testing is ensuring that the code is usable.
To make code testable is also a design exercise: you need to make decisions about the design of your program when you write your tests. If you have no idea how to test it,
you are equally clueless about how to use the designed classes.
====

== Links

* https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests[JUnit 5 Parameterized Tests ^]
* https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource[CSV Source Tests ^]
* https://www.baeldung.com/parameterized-tests-junit-5[Baeldung on Parameterized Tests with JUnit 5 ^]