---
title: "01 Unit Testing Basics"
description: ""
date: 2022-02-01T11:32:04+01:00
draft: false
images: []
slug: "unit-testing-basics"
menu:
  docs:
    parent: ""
weight: 010
toc: true
---

== Write your own tests!

[big]#Throughout the exercises of PRC1, you have become acquainted with the value of tests: You have a way of checking if your code is any good without having to
test each and every part manually. You clicked on the nice TestMyCode (TMC) button in Visual Studio Code (VSC) and then you could see which parts of your code worked, and which didn't.
There is a catch though: Out there in the real world, there won't be any button doing that magic for you, nor will some teacher or school
provide the tests for you, so [red]*you will be on your own*.#

But fret not! Writing tests is typically much simpler than writing the actual code. At least it is, when you know the anatomy of a test:

. [blue]**A**rrange: Prepare or set up the thing you want to test
. [blue]**A**ct: Interact with the object you are testing
. [blue]**A**ssert that the observable result(s) is/are as expected

Finally, if a test says [red]*boom*, then at least you learned something ...

// :sectums!:
// == Reading
// :sectnums:
//
// We assume that PRC1 covers the content of chapters 1 through 6 of Horstmann sufficiently. It does
// not hurt to skim through those first. We will introduce no new _java_ topics this week, but use
// in but use whatever was there up until week 11 o
//
//
// * Horstmann Core Java, Ed 11, Vol 1 Fundamentals Chapter 5 sections 5.1-5.5
// //* Horstmann Core Java, Ed 11, Vol 2 Advanced Feature
//

*Topics week 1*

* Test Driven Development.
* Maven configuration as exercise.
* **A**rrange **A**ct **A**ssert.
* JUnit (5) as test framework.
* AssertJ as assertion library.

// On the theory of inheritance and interfaces. we will refine later on.

== Testing / Test Driven Development

include::{topics}/tdd.adoc[]

include::{topics}/arrangeactassert.adoc[]

include::{topics}/assertjexamples.adoc[]

include::{topics}/softassertions.adoc[]

include::{topics}/assumptions.adoc[]

== Additional pointers

* https://assertj.github.io/doc/[AssertJ - fluent assertions java library ^]
* https://junit.org/junit5/docs/current/user-guide/[JUnit 5 User Guide ^]

[NOTE]
====
Check out https://assertj.github.io/doc/#assertj-core-assertions-guide[this guide on assertions with AssertJ]!
====

== Clean tests
Bad tests are anything but a pleasure to work with. They are slow, hard to understand, and hard to maintain.
In order to write clean tests, we follow the F.I.R.S.T. principles of tests:

// Source: Clean code, Robert C. Martin

- **Fast**: Tests should run quickly.
- **Independent**: Tests should not depend on each other. When the state of one test affects the outcome of another, it can be hard to understand why a test fails and makes it harder to run single tests or run tests in parallel.
- **Repeatable**: Tests should be repeatable in any environment. This means that tests should not depend on external resources like databases, network, or file systems.
- **Self-Validating**: Tests should be able to determine if they pass or fail without human intervention. This means that the test should contain assertions that determine if the test passes or fails.
- **Timely**: Tests should be written before the code they test. This is the essence of Test-Driven Development (TDD). If you write tests after the code, you might find out the code is hard to test.

include::{topics}/parameterizedtests.adoc[]

[TIP]
====
Think test driven! So write tests FIRST, and then code. Testing is ensuring that the code is usable.
To make code testable is also a design exercise: you need to make decisions about the design of your program when you write your tests. If you have no idea how to test it,
you are equally clueless about how to use the designed classes.
====

== Links

* https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests[JUnit 5 Parameterized Tests ^]
* https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource[CSV Source Tests ^]
* https://www.baeldung.com/parameterized-tests-junit-5[Baeldung on Parameterized Tests with JUnit 5 ^]