== Arrange Act Assert

.Some action.
video::GJFGXYyKvns[youtube]

When designing tests it is good to keep the ideas of making _action movies_ in the back of your head.
Looking at some _the making of..._ can be quite instructive in this case.
For a scene to be taken, there is typically quite some preparation involved like hanging Spiderman
on a thin cable from the ceiling, making sure the *crook* is in the right position so he can land or receive the first punches and so on. +
Then the director calls *action* and the scene is acted out +
If the director is satisfied, all is okay +
If not, he will want a redo later on. 

A very popular style to write unit tests is the triple-A or *Arrange-Act-Assert*.

[blue]*Arrange* simply means that you set up the objects you need in the tests:

** The **S**ystem **U**nder **T**est, the [blue,bold]**SUT** its the term in the tesing world. In movies it is the protagonist or main actor.
** The **D**ependent **O**n **C**omponents or [blue,bold]**DOC**s, the scenario needs to play out the action. Supporting actors or even props in the movies.

[blue]*Act* is quite similar to a film directory shouting *action*, that is do what you prepared for. +

**  This typically is one method call on the SUT.

[blue]*Assert* to test if the actual result of the action is what is expected. +

**  The actual value can be the return value of the called method, but also the (new) state of the SUT. +
  In the movie: did the explosion happen, was the punch landed correctly
  and was the emotion credible.

.AAA in action
[source,java]
----
@Test
public void shouldAllowToAddAddress() {
  // Arrange
  Client client = new Client();
  Address addressA = new Address(221b, "Baker Street");

  // Act
  client.addAddress(addressA);

  // Assert
  assertThat( client.getAddresses() ).contains( addressA ));
}
----

Of course, Arrange, Act and Assert will vary with the actual business requirement, much
as the setup, play, and act in movie making. And also, quite similar to movie making
the arrange can be expensive or cheap, the action be fraught with risk or easy, and the assert can be complex or simple.

We hope to teach to keep all three _as simple as possible_, to keep the costs of testing so low that to make it never an argument to skip testing.

Later in this course we see some more complex scenarios, in which we need https://en.wikipedia.org/wiki/Extra_(acting)[Extras] as one would say in the movie industry.

== Clues needed

A smart person is able to avoid work. A common strategy is to let others do it. You can achieve such smartness your selves by using your tools properly.

For instance your IDE will gladly [green]_complete_ code that your started by showing
a list of possible completions of the code that you already provided. However, the IDE
can only do that if you provide it with sufficient clues. For instance when you want the IDE
to generate a non-existing generic class, create two instance with different type parameters before your accept the hint to create class.

.complete a generic
[source,java]
----
// on the next line the compiler complains about nonexisting Box class.
Box<String> sb= new Box<String>(); 
// on the next line the compiler complains about nonexisting Box class.
Box<Integer> ib= new Box<Integer>(); 
// now you can let the IDE to follow its urge to do the typing for you.
----

The same applies to methods. If you want a specific return type, provide that in a declaration where you specify such type.

It also applies to frameworks such as AssertJ, that provides an `assertThat(...)` method as entry for almost all asserts.
But what you put on the dots is important, because the IDE will inspect the [blue]*type* of the _expression_ and then will look for the possible
completions. The completions for an Integer or int are very different from those for a `Collection` or `Iterable`.

Combine this with the previous tip. First you specify a variable with a type, that
uses the variable inside the `assertThat(...)` and then the IDE will be able to find the possible completions.

Sometimes you have to nudge the IDE a bit, for instance when it suggest to create two constructors from the above example.
Accept one of the suggestions, but then _modify_ the generated constructor to accept the type parameter of the class as input type of the constructor.
After saving all files, you will have convinced both IDE and compiler.

[TIP]
====

.It is good to have a thinking pause
Let the IDE and framework do (most) of the typing work for you, by providing clues. If you do that smartly, it
will be easy to write code that is correct and acceptable by the compiler. A thinking pause can also useful 
 for the IDE, for it might need some processing first to find possible completions.
[big]*Being lazy is good, both for code and smart people.*
====
