== Informatics pom

Spelled all lower  case: `informaticspom`, is a super pom to use in Fontys Venlo projects. It keeps your own pom.xml file simple and focused to declare just the
dependencies needed. Niceties to do proper Test Driver Development are provided for in the informaticspom definitions, including things as being able to create
javadoc in a professional looking way, including code highlighted code snippets, checkstyle, reporting, code coverage with maven, pmd, spotbugs  etc.

https://github.com/FontysVenlo/informaticspom[informaticspom is hosted on github].

This way of using maven, having a [blue]#super# or parent pom defined globally (in a repository, not on a local path), is the [big black]#modern# usage.
 It can be seen in well known big java projects such as https://spring.io/projects/spring-boot[Spring Boot] and https://quarkus.io/[quarkus], to name two contenders in the java-web technology world.

[TIP,role="green"]
====
Note that we are using a _separately installed_ maven (3.9.6 at the time of writing) which you can download from http://maven.apache.org/download.cgi[apache maven],
  not the one bundled with NetBeans or any other IDE. You can tell NetBeans (via tools-> options-> java-> maven) to use the installed one instead of the bundled one. (Mac users go to NetBeans-> Preferences -> ... again).

[big]_Our tests will [blue]#always# use maven, not some IDE. There is no gnome inside the build server to move the mouse._
====

[[informaticspom-as-parent]]
.Setting informaticspom as parent.
[source,xml]
----
    <parent>
      <groupId>io.github.fontysvenlo</groupId>
      <artifactId>informaticspom</artifactId>
      <version>1.2</version>
      <relativePath/> // <!--1-->
    </parent>
----

<1> The parent pom does not live in a local directory near (relative to) the project, but instead in a repository. This makes a parent pom 'portable'. All of the starter projects we provide already use this parent in some version.

If you want to use informaticspom in your own project, copy the parent definition into your project's pom file. Add additional dependencies as required.
