== Maven

From week two onwards we will use https://books.sonatype.com/mvnref-book/reference/index.html[Maven] as the preferred build tool. The link in the previous sentence
points to the very readable complete reference manual, which also has some pointers for beginners, might you categorize yourselves as one.

=== Maven Repositories

A maven repository is a server that provides ready built maven 'artifacts', such as (binary) jar files containing libraries, frameworks or APIs and in many (but not all) companion jar files containing the javadoc (often) and sources of the same binary. A maven repository is *NOT* a source code management system (CMS),footnote:[Guess why] although it typically holds several versions of a binary, and there are tools, such as https://www.sonatype.com/nexus-repository-sonatype[Nexus Repository Manager]. +

There is a default repository, called https://mvnrepository.com/repos/central[maven central]. You (as a team or company) can have your own repository.

If you look at a maven repository you will see that it is organized along the three axes: groupId, artifactId and version. We have published our Fontys Venlo *informatics pom* under groupId io.github.fontysvenlo, artifactId informaticspom and current (February 2024) 1.2.
