== Transactions

Things that can go wrong will go wrong. This problem is aggravated by having to use multiple _things_.
Murphy says hello again :-).

A *transaction* is defined as a sequence of operations that can either succeed completely or be undone
without any residual effect. +
In plain English: It either happens fully, or we can forget about it.

For a persistence layer that means: if it cannot fulfill the obligation it should
make sure that nothing happens to compromise the data already stored _before_ the transaction.

The simple explanation of how this works is that the party that is busy with a resource gets
the resource all for itself, locking any other parties out.
If something fails, the mess created can either be undone (rollback) or not committed, which in effect is the same.

Locking out sounds serious, and it is, on multiple accounts.

* When using a [big]*BIG* lock, as locking out all other parties, things become [big]_VERY_ slow.
* When lock less, like just a table, or better still, only the records we want to modify, then
  [big]**DEAD**locks can occur, which is even more problematic than having to wait.
* In all cases, when something goes awry, one may have to clean up mess in multiple places.

All this can be related to quite difficult problems. Luckily there are solutions to that and,
not unimportant, as far as the database goes, that can typically deal with the issues pretty well. Have a look at paragraph 5.9 for more information about transaction programming.
